require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 90

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'app/views/**/*.rb'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Rails/Output:
  Exclude:
    - 'app/views/**/*.rb'

Style/Documentation:
  Exclude:
    - '**/*'
